milestone2/config/routes.rb
Rails.application.routes.draw do
  resources :info_queries

root 'info_finder#index'

get 'info_finder' => 'info_finder#index', as: :info_finder
post 'info_ana' => 'info_ana#index', as: :info_ana
get 'info' => 'info_finder#test'

end

milestone2/app/models/case.rb
class Case < ActiveRecord::Base
  has_many :involves
  has_many :parties, :through => :involves
end

milestone2/app/models/en_banc_review.rb
class EnBancReview < ActiveRecord::Base
end

milestone2/app/models/info_query.rb
class InfoQuery < ActiveRecord::Base
       #params: is_owner, user_size, oppo_size, user_loc, oppo_loc, law_issue, tech_area, judge1, judge2, judge3

end

milestone2/app/models/involve.rb
class Involve < ActiveRecord::Base
  belongs_to :party
  belongs_to :case
end

milestone2/app/models/party.rb
class Party < ActiveRecord::Base
  has_many :involves
  has_many :cases, :through => :involves
end

milestone2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

milestone2/app/controllers/info_ana_controller.rb
class InfoAnaController < ApplicationController
end

milestone2/app/controllers/info_finder_controller.rb
class InfoFinderController < ApplicationController

      def test 
      	  @a = 1;
	  @b = 2;
      end
end

milestone2/app/controllers/info_queries_controller.rb
class InfoQueriesController < ApplicationController
  before_action :set_info_query, only: [:show, :edit, :update, :destroy]

  # GET /info_queries
  # GET /info_queries.json
  def index
    @info_queries = InfoQuery.all
  end

  # GET /info_queries/1
  # GET /info_queries/1.json
  def show
  end

  # GET /info_queries/new
  def new
    @info_query = InfoQuery.new
  end

  # GET /info_queries/1/edit
  def edit
  end

  # POST /info_queries
  # POST /info_queries.json
  def create
    # current info_query
    @info_query = InfoQuery.new(info_query_params)
    @test = "a test"
    #render "/info_queries/test.html.erb"
    #return
    respond_to do |format|
      if @info_query.save
        format.html { redirect_to @info_query,  notice: 'Info query was successfully created.' }
        format.json { render :show, status: :created, location: @info_query }
      else
        format.html { render :new }
        format.json { render json: @info_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info_queries/1
  # PATCH/PUT /info_queries/1.json
  def update
    respond_to do |format|
      if @info_query.update(info_query_params)
        format.html { redirect_to @info_query, notice: 'Info query was successfully updated.' }
        format.json { render :show, status: :ok, location: @info_query }
      else
        format.html { render :edit }
        format.json { render json: @info_query.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info_queries/1
  # DELETE /info_queries/1.json
  def destroy
    @info_query.destroy
    respond_to do |format|
      format.html { redirect_to info_queries_url, notice: 'Info query was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info_query
      @info_query = InfoQuery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_query_params
      params.require(:info_query).permit(:is_owner, :user_size, :oppo_size, :user_loc, :oppo_loc, :law_issue, :tech_area, :judge1, :judge2, :judge3)
    end

    # define function for query 1
    def find_percent(info) 
    	win = 0
	total = 0
    	@cases = Case.find(:issue => info.law_issue)
	@user_parties = Party.find(:size => info.user_size)
	@oppo_parties = Party.find(:size => info.oppo_size)
	@involves = @user_parties.involves
	@
    end     

    
end

milestone2/app/helpers/application_helper.rb
module ApplicationHelper
end

milestone2/app/helpers/info_ana_helper.rb
module InfoAnaHelper
end

milestone2/app/helpers/info_finder_helper.rb
module InfoFinderHelper
end

milestone2/app/helpers/info_queries_helper.rb
module InfoQueriesHelper
end

milestone2/app/views/info_ana/index.html.erb
<head>
<h1>Find your best Judge choice!</h1>
</head>

<body>

</body>

milestone2/app/views/info_finder/index.html.erb
<head>
<center>	
<h1>Law Infomation Finder</h1>
</center>
</head>

<body>
<!--generate two button to two other pages-->
<br><br>
<table width=90% align=center>
<tr bgcolor="#ffeeee">
<td><b>Please Choose</b></td>
</tr>



<tr bgcolor="eeeeff">
<td> <center><%= button_to 'Find Case Information', new_info_query_path, method: :get %> </center></td>
<td> <center><%= button_to 'Analyse Judge Preference', info_ana_path %> </center></td>
</tr>




</body>

milestone2/app/views/info_finder/test.html.erb
<%= @a %>
<%= @b %>

milestone2/app/views/info_queries/_form.html.erb
<%= form_for(@info_query) do |f| %>
  <% if @info_query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info_query.errors.count, "error") %> prohibited this info_query from being saved:</h2>

      <ul>
      <% @info_query.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :is_owner, "Are you a patent owner?" %><br>
    <%= f.check_box :is_owner %>
  </div>
  <div class="field">
    <%= f.label :user_size, "Please input your company size" %><br>
    <%= f.number_field :user_size %>
  </div>
  <div class="field">
    <%= f.label :oppo_size, "Please input your opponent company size" %><br>
    <%= f.number_field :oppo_size %>
  </div>
  <div class="field">
    <%= f.label :user_loc, "Please input your company location" %><br>
    <%= f.text_field :user_loc %>
  </div>
  <div class="field">
    <%= f.label :oppo_loc, "Please input your opponent company location" %><br>
    <%= f.text_field :oppo_loc %>
  </div>
  <div class="field">
    <%= f.label :law_issue, "Please input your patent law issue of the lawsuit" %><br>
    <%= f.text_field :law_issue %>
  </div>
  <div class="field">
    <%= f.label :tech_area, "Please input your technical area of the lawsuit" %><br>
    <%= f.text_field :tech_area %>
  </div>
  <p>Please input the names of the judges that will hear the case</p>
  <div class="field">
    <%= f.label :judge1 %><br>
    <%= f.text_field :judge1 %>
  </div>
  <div class="field">
    <%= f.label :judge2 %><br>
    <%= f.text_field :judge2 %>
  </div>
  <div class="field">
    <%= f.label :judge3 %><br>
    <%= f.text_field :judge3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

milestone2/app/views/info_queries/edit.html.erb
<h1>Editing info_query</h1>

<%= render 'form' %>

<%= link_to 'Show', @info_query %> |
<%= link_to 'Back', info_queries_path %>

milestone2/app/views/info_queries/index.html.erb
<h1>Listing info_queries</h1>

<table>
  <thead>
    <tr>
      <th>Is owner</th>
      <th>User size</th>
      <th>Oppo size</th>
      <th>User loc</th>
      <th>Oppo loc</th>
      <th>Law issue</th>
      <th>Tech area</th>
      <th>Judge1</th>
      <th>Judge2</th>
      <th>Judge3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @info_queries.each do |info_query| %>
      <tr>
        <td><%= info_query.is_owner %></td>
        <td><%= info_query.user_size %></td>
        <td><%= info_query.oppo_size %></td>
        <td><%= info_query.user_loc %></td>
        <td><%= info_query.oppo_loc %></td>
        <td><%= info_query.law_issue %></td>
        <td><%= info_query.tech_area %></td>
        <td><%= info_query.judge1 %></td>
        <td><%= info_query.judge2 %></td>
        <td><%= info_query.judge3 %></td>
        <td><%= link_to 'Show', info_query %></td>
        <td><%= link_to 'Edit', edit_info_query_path(info_query) %></td>
        <td><%= link_to 'Destroy', info_query, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info query', new_info_query_path %>

milestone2/app/views/info_queries/new.html.erb
<title bgcolor="eeeeff">
<center>
<h1>New info_query</h1>
</center>
</title>

<h3>Please input basic information: </h3>
<%= render 'form' %>

<%= link_to 'Back', info_queries_path %>

milestone2/app/views/info_queries/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Is owner:</strong>
  <%= @info_query.is_owner %>
</p>

<p>
  <strong>User size:</strong>
  <%= @info_query.user_size %>
</p>

<p>
  <strong>Oppo size:</strong>
  <%= @info_query.oppo_size %>
</p>

<p>
  <strong>User loc:</strong>
  <%= @info_query.user_loc %>
</p>

<p>
  <strong>Oppo loc:</strong>
  <%= @info_query.oppo_loc %>
</p>

<p>
  <strong>Law issue:</strong>
  <%= @info_query.law_issue %>
</p>

<p>
  <strong>Tech area:</strong>
  <%= @info_query.tech_area %>
</p>

<p>
  <strong>Judge1:</strong>
  <%= @info_query.judge1 %>
</p>

<p>
  <strong>Judge2:</strong>
  <%= @info_query.judge2 %>
</p>

<p>
  <strong>Judge3:</strong>
  <%= @info_query.judge3 %>
</p>

<%= link_to 'Edit', edit_info_query_path(@info_query) %> |
<%= link_to 'Back', info_queries_path %>

milestone2/app/views/info_queries/test.html.erb
<p><%= @test%></p>

milestone2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Milestone2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>